feat : NG_BACK_END-119
nrhirano/school011 pull request #1
Opened 2021-12-13 11:25 UTC by nrhirano

#### 関連タスク
- [NG_BACK_END-119 【第11回スクール宿題】 (平野様)](https://nishio-pj.backlog.com/view/NG_BACK_END-119)

#### PR 概要
- 第11回スクールの宿題です。

#### 相談したい項目・保留した項目
- 問題4を解くことができなかったので、次回の勉強会でレクチャーをお願い致します。

#### 参考資料
- なし

2021-12-14 02:48 UTC, EikoNakashima commented on homework011/channel-buffering.go
> +	ch := make(chan string)
```suggestion
	ch := make(chan string)
```

`var i int`
は定義しなくてもいいと思います。

2021-12-14 02:48 UTC, EikoNakashima commented on homework011/channel-buffering.go
> +		fmt.Print(v, "言語\n")
```suggestion
		fmt.Printf("%s言語\n", <-ch)
```
こういう書き方も出来ます。

2021-12-14 02:49 UTC, EikoNakashima commented on homework011/channel-buffering.go
> +	for i = 0; i <= 3; i++ {
```suggestion
	for i := 0; i <= 3; i++ {
```

2021-12-14 03:19 UTC, EikoNakashima requested changes

2021-12-14 03:19 UTC, EikoNakashima commented on homework011/xorm-student.go
> +		}
```suggestion
	for _, student := range students {
	
```

と書きましょう。
i <= 2　にしていると、studentが増えたら破綻してしまします。
また、少し助長です。

2021-12-15 01:53 UTC, EikoNakashima requested changes
コメントしました。

2021-12-15 01:53 UTC, EikoNakashima commented on homework011/xorm-student.go
> +	var i int
```suggestion
```

いらないです。

2021-12-15 01:53 UTC, EikoNakashima commented on homework011/xorm-student.go
> +		}
```suggestion
```
studentは上で定義しているので、いらないです。
studentsの配列の中身のstudentに値も全て入っています。
for range文はソースコードに良く出てくるので、少し復習された方が良いかもしれません。。。

2021-12-15 02:32 UTC, GenkiHirano commented on homework011/channel-select.go
> +	fmt.Println("finish!")
![badge](https://img.shields.io/badge/review-imo-orange.svg)
receiveValue関数のquitで、even、odd、sumと同じように出力した方が綺麗かなと思います。

2021-12-15 02:32 UTC, GenkiHirano commented on homework011/channel-select.go
> +	for i := 0; i < len(s); i++ {
![badge](https://img.shields.io/badge/review-imo-orange.svg)
こちらのfor文は、`s`の要素数ではなく中身を回したいです。

2021-12-15 02:34 UTC, GenkiHirano commented on homework011/channel-select.go
> +	for {
👍

2021-12-16 01:22 UTC, GenkiHirano commented on homework011/channel-select.go
> +	for i := 0; i < len(s); i++ {
こちら対応お願い致します。

2021-12-16 01:22 UTC, GenkiHirano commented on homework011/channel-select.go
> +	fmt.Println("finish!")
こちら対応お願い致します。

2021-12-16 01:37 UTC, EikoNakashima approved these changes
Gemcook平野のレビュー以外はOKです。

2021-12-17 01:17 UTC, GenkiHirano approved these changes
LGTM 🎄

2021-12-17 01:22 UTC, merged